### ISSUE TITLE
Only Coding VNTRs were genotyped

### ISSUE THREAD

**Issue by npatel22526** [mehrdadbakhtiari/adVNTR#18]
Hello Mehrdad, 

We started analyzing the adVNTR output bed files and it turned out that it only contains coding or near coding VNTRs. Is it default to only use coding VNTRs ?  Is there is a specific flag that needs to be set to turned on/off such behavior ? 

Thanks, 
Nick

**Comment by mehrdadbakhtiari** [comment]
This issue is discussed in #17.  I have updated the code and documentation to resolve this problem so this behavior is always off.
