### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by wdecoster** [mehrdadbakhtiari/adVNTR#2]
Hi,

I'd like to try your tool, looks really interesting. I noticed the README describes Python2.7, but is there any reason it wouldn't work for Python3?

Cheers,
Wouter

**Comment by mehrdadbakhtiari** [comment]
Hi Wouter,

Thank you for your interest in adVNTR! We have only tested adVNTR with Python2.7, however, it should work with Python3 as well. Let me know if you faced any issues and I'm happy to help.

Best,
Mehrdad

**Comment by wdecoster** [comment]
Hi Mehrdad,

I'll install and try. I'd recommend you submit this also to PyPI and/or (bio)conda for convenient installation.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Hi Mehrdad,

Attempting to run advntr.py resulted in the error below:

```
$ python advntr.py 
Traceback (most recent call last):
  File "advntr.py", line 3, in <module>
    from src.commands import genotype, not_implemented_command
  File "/home/wdecoster/bin/adVNTR/src/commands.py", line 5, in <module>
    from genome_analyzer import GenomeAnalyzer
ModuleNotFoundError: No module named 'genome_analyzer'
```

I think the solution to this (python3) issue is described in this StackOverflow thread: https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

**Comment by mehrdadbakhtiari** [comment]
Thank you for reporting the import problem and its solution.
I'll create another issue for installation through PyPI and I will work on that.

**Comment by wdecoster** [comment]
Thanks for the quick fix! I'll install it again.
If you need help anywhere give me a shout.

Cheers,
Wouter
