### ISSUE TITLE
Issues running advntr genotype

### ISSUE THREAD

**Issue by aob93** [mehrdadbakhtiari/adVNTR#35]
Hi,

After installing the package, I'm having difficulty getting the genotype command to run on some pacbio bam files. 

Running the following;

advntr genotype -p -a NA07019_SC034768.bam --update -m vntr_data/hg19_VNTRs.db -o bed --working_directory test/

Produces;

Traceback (most recent call last):
  File "/opt/miniconda2/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda2/lib/python2.7/site-packages/advntr/__main__.py", line 121, in main
    genotype(args, genotype_parser)
  File "/opt/miniconda2/lib/python2.7/site-packages/advntr/advntr_commands.py", line 91, in genotype
    reference_vntrs = load_unique_vntrs_data()
  File "/opt/miniconda2/lib/python2.7/site-packages/advntr/models.py", line 125, in load_unique_vntrs_data
    right_flanking, repeats, scaled_score FROM vntrs''')
sqlite3.OperationalError: no such table: vntrs

I'm at a bit of a loss here as to what is the issue. Any help is greatly appreciated.

**Comment by mehrdadbakhtiari** [comment]
Hello,
Could you please check the content of vntr_data that you downloaded? I guess you should either use `-m hg19_selected_VNTRs_Pacbio.db` or `-m hg19_genic_VNTRs.db` (probably not `-m vntr_data/hg19_VNTRs.db`) depending on which vntr_data you have downloaded.
Let me know how it goes and I'd be happy to help if the issue persist.

**Comment by aob93** [comment]
Thanks! that seems to have worked, although the command runs without any errors and produces no output so I assume I'm still not quite there. 

Also, I can only install and run v1.2 via conda. v1.4 would be my preference but installing from source has not proved fruitful. Any suggestions?

**Comment by mehrdadbakhtiari** [comment]
Great! Please use `--outfmt bed --outfile sample.bed` to get the output. There is a typo in the command you wrote which doesn't quite specify the output format and output file.

With regard to version, are you using Linux? there have been some issues with conda on linux about installing the latest version and many packages have that issue. I'll update you once it is solved.
Meanwhile, you can try to install from source by running only [this commands](https://advntr.readthedocs.io/en/latest/installation.html#to-install). Since you have installed the older version with conda, you shouldn't have any problems with requirements and `python setup.py install` should take care of everything. I haven't tried this myself but I think it worth a shot.

**Comment by aob93** [comment]
Will do! 

I'm on Mac. Trying installing from source and then calling advntr results in the following error;

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

I believe Tensor Flow 2.2 is incompatible with the python v2.

**Comment by mehrdadbakhtiari** [comment]
Sorry about confusion. I thought you are using Linux, conda was working on Mac when I tested.
@Jong-hun-Park Can you look into the issue when conda doesn't install the latest version on Mac? Thanks

**Comment by aob93** [comment]
Hi again Mehrdad,

I've managed to have a bit more success having installed v1.3 from source.

I'm trying to genotype 2 custom VNTRs and I'm happy that advntr addmodel is running properly. adVNTR genotype however is outputting strange results.

Here is my command and output;

`advntr genotype -a NA07019_SC034768.clean.bam -m vntr_data/hg38_VNTRs.db -p --working_directory test

[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
/opt/miniconda2/lib/python2.7/site-packages/advntr-1.3.3-py2.7-macosx-10.7-x86_64.egg/advntr/vntr_finder.py:401: RuntimeWarning: invalid value encountered in double_scalars
1
None
2
None
`
Looking at the .log file, it is clear that the tool is able to find and count the repeats, but is having trouble converting this into a genotype, with Maximum probability for genotyping: 1e-20 for both VNTRs I'm querying. 

Is this something you have came across before and would you have any suggestions to get a genotype?

Thanks again!

**Comment by mehrdadbakhtiari** [comment]
Hello,
I'm glad you could finally install a newer version. Yes this output basically means adVNTR is unable to genotype these two loci. Could you please email me the log file so I can take a look (at least the parts that don't contain read sequences if that's not public)? 
What I can say now is either they have a very short pattern and high number of repeats (long overall length) or there are more than one copy of those VNTRs in the genome and it's not easy to distinguish between them. I'd be happy to look more and fix the issue if it's something else.

**Comment by aob93** [comment]
No problem at all, have you a preferred email address?

**Comment by aob93** [comment]
Thanks again for your help, much appreciated!

Here’s an example of a log file. There are no read sequences, just motif counts so all good!

Best,
Aidan

**Comment by mehrdadbakhtiari** [comment]
Hi Aidan,

Sorry but it seems that github doesn't include attachments when you respond by email. Could you directly send it as an email to mehrdad.baxtiari@gmail.com?
Thanks
