### ISSUE TITLE
vcf Output-Filter is all . instead of PASS

### ISSUE THREAD

**Issue by psychrb** [mehrdadbakhtiari/adVNTR#41]
In running adVNTR I am concerned since the FILTER column for the output vcf file is all "." for the n=6,719 loci.
Please advise: This should all be "PASS", instead no?? Does this mean that these calls did not PASS?
The header of adVNTR output vcf file is below and input code as per program:
advntr genotype -m hg19_selected_VNTRs_Illumina.db -f FILENAME.bam --of vcf -o FILE.vcf

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	FILENAME
chr1	700243	.	CGAGGCGGGAAGATCACTTGATATCAGGAGTCGAGGCGGGAAGATCACTTGACGTCAGGAGTT	.	.	.	END=700306;VID=156;RU=CGAGGCGGGAAGATCACTTGACATCAGGAGTT;RC=2GT:DP:SR:FR:ML	0/0:18:6:12:0.9995
chr1	777293	.	AGAAATGCTTCTTTAGAAATGCTTCTTT	.	.	.	END=777321;VID=174;RU=AGAAATGCTTCTTT;RC=2	GT:DP:SR:FR:ML	0/0:32:18:14:1.0000
chr1	900683	.	TTTATTTAGTTGTTTATTTATTTAGTTATTTATCTTATTTATTGAGGGG	.	.	.	END=900732;VID=239;RU=TTTATTTAGTTATTTA;RC=3	GT:DP:SR:FR:ML	0/0:28:15:13:1.0000
chr1	910475	.	GAGAAAGAAAAAAGAGAGAAGAGAGAGAGGAGAAGAGAGAAAAGAAGAGAAGAGAGAAGAGAAGAGAAGGAAAGAGAGAGAGAGAATAAGAAAAGGAAGAAAGAAAAAGAAAAGATAGAA

**Comment by Jong-hun-Park** [comment]
Hi,
"." for FILTER column means there is no filter applied. Since adVNTR doesn't automatically apply QC steps after calling genotypes, it's set to the missing value, ".".
