### ISSUE TITLE
subset hg19_genic_VNTRs.db

### ISSUE THREAD

**Issue by psychrb** [mehrdadbakhtiari/adVNTR#43]
Can you please clarify advise? For genotyping a specific subset of VNTRs from the n=158,522 VNTRs loci (i.e. a subset of the hg19_genic_VNTRs.db within vntr_data_genic_loci.zip):
1) Can the VNTRs be subsetted by specific VNTRs of interest within, if I specify chromosome and coordinates?? 
2) This input code could then just include this subsetted reference file...correct?
advntr genotype -m vntr_data subsettedfile.db -f filename.bam --working_directory ./ -of vcf -o filename_advntr.vcf
Thanks.

**Comment by Jong-hun-Park** [comment]
Yes, you can use a customized set of reference VNTRs. If you selected a subset of vntr_data_genic_loci.zip, it should work.

**Comment by Jong-hun-Park** [comment]
Yes, you can use a customized set of reference VNTRs. If you selected a subset of vntr_data_genic_loci.zip, it should work.
