### ISSUE TITLE
:ref:`add-custom-vntr-label` not found in the README.rst

### ISSUE THREAD

**Issue by nh13** [mehrdadbakhtiari/adVNTR#6]
It would be great how to add custom VNTRs to use adVNTR.

**Comment by clamp131** [comment]
Do you solve the problem? I also want to construct my own VNTRs.

**Comment by mehrdadbakhtiari** [comment]
Dear @clamp131,
Please see `advntr addmodel --help` in the latest version of advntr.
You can define custom VNTRs, and it may take around 30 minutes for tool to run the process to train the recruitment scores. Let me know if you face with any difficulties.

**Comment by clamp131** [comment]
I see. Thank you.

**Comment by mehrdadbakhtiari** [comment]
Now the link works and points to the correct documentation.
Thank you for bring this to my attention.
