### ISSUE TITLE
why is python >= 3.7 skipped during build?

### ISSUE THREAD

**Issue by yangxingyu588** [mehrdadbakhtiari/adVNTR#66]
why is `python >= 3.7` skipped in [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/d0879b8111b6ccdb343fb027bddca6a064febe67/recipes/advntr/meta.yaml#L8) during build?

**Comment by Jong-hun-Park** [comment]
There is a conflict with another dependent package.
