### ISSUE TITLE
muscle is not listed as a requirement

### ISSUE THREAD

**Issue by nh13** [mehrdadbakhtiari/adVNTR#9]
See `MUSCLE_DIR` in `settings.py`.  It failed fairly far into the execution saying that it could find the muscle directory (is it the executable or directory???)

**Comment by mehrdadbakhtiari** [comment]
Hi Nils,
Muscle was not included as requirements as its executable binary was included in the project. Thanks for your suggestion, I removed `MUSCLE_DIR` and executable bin, and added it as a requirement which makes everything more clear.

Best,
Mehrdad
